/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CSSInserter
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  css: [
    { name: "Chapter number", tag: "h2", class: "chapter-number", style: "font-size: 4em", contextMenu: false },
    { name: "No indent", tag: "p", class: "no-indent", style: "text-indent: 0", contextMenu: false },
    { name: "Yellow highlight", tag: "span", class: "highlight", style: "background-color: #fff88f; color: black", contextMenu: true },
    { name: "Green highlight", tag: "span", class: "highlight", style: "background-color: #1EFF00; color: black", contextMenu: true },
    { name: "Nothing", tag: "span", class: "", style: "", contextMenu: false }
  ]
};
var GeneralSettingsTab = class extends import_obsidian.PluginSettingTab {
  /* constructor(app: App, plugin: CSSInserter) {
      super(app, plugin);
      this.plugin = plugin;
  } */
  display() {
    const { containerEl } = this;
    this.clearHtml();
    containerEl.empty();
    containerEl.createEl("p", { text: "CSS snippets to be applied to the selected text:" });
    const settingHeader = containerEl.createDiv({ cls: "setting-header" });
    settingHeader.createDiv({ text: "Name", cls: "value-header" });
    settingHeader.createDiv({ text: "Tag", cls: "tag-header" });
    settingHeader.createDiv({ text: "Class", cls: "value-header" });
    settingHeader.createDiv({ text: "Style", cls: "style-header" });
    settingHeader.createDiv({ text: "", cls: "contextMenu-header" });
    let containerButton = settingHeader.createEl("div", { cls: "container_add_button" });
    let addCSSButton = containerButton.createEl("button", { text: "Add CSS Snippet" });
    const settingContainer = containerEl.createDiv();
    addCSSButton.onclick = (ev) => this.addCSS(settingContainer);
    this.plugin.settings.css.forEach((s, i) => this.addCSS(settingContainer, i + 1));
    this.addInstructions(containerEl);
  }
  clearHtml() {
    setTimeout(() => {
      removeClass("setting-item");
      removeClass("setting-item-info");
      removeClass("setting-item-control");
      deleteContainer(".setting-item-description");
    }, 0);
    function removeClass(className) {
      document.querySelectorAll("." + className).forEach((i) => i.removeClass(className));
    }
    function deleteContainer(selector) {
      document.querySelectorAll(selector).forEach((i) => {
        var _a;
        return (_a = i.parentElement) == null ? void 0 : _a.remove();
      });
    }
  }
  addCSS(containerEl, counter) {
    this.clearHtml();
    const { css } = this.plugin.settings;
    const settingItemContainer = containerEl.createDiv({ cls: "setting-item-container" });
    const cssCounter = counter != null ? counter : css.length + 1;
    if (!counter) {
      const newCSS = { name: "Yellow highlight", tag: "span", class: "highlight", style: "background-color: #fff88f; color: black", contextMenu: false };
      css.push(newCSS);
      this.plugin.addCSSCommand(newCSS, cssCounter);
      this.plugin.saveSettings();
    }
    const currentCSS = css[cssCounter - 1];
    new import_obsidian.Setting(settingItemContainer).setClass("css-inserter-setting-item").addText((text) => {
      return text.setValue(currentCSS.name).onChange(async (value) => {
        currentCSS.name = value;
        await this.plugin.saveSettings();
        this.plugin.addCSSCommand({
          name: value,
          tag: currentCSS.tag,
          class: currentCSS.class,
          style: currentCSS.style,
          contextMenu: currentCSS.contextMenu
        }, cssCounter + 1);
      });
    });
    new import_obsidian.Setting(settingItemContainer).setClass("css-inserter-setting-item-tag").addText((text) => {
      return text.setValue(currentCSS.tag).onChange(async (value) => {
        currentCSS.tag = value;
        await this.plugin.saveSettings();
        this.plugin.addCSSCommand({
          name: currentCSS.name,
          tag: value,
          class: currentCSS.class,
          style: currentCSS.style,
          contextMenu: currentCSS.contextMenu
        }, cssCounter + 1);
      });
    });
    new import_obsidian.Setting(settingItemContainer).setClass("css-inserter-setting-item").addText((text) => {
      return text.setValue(currentCSS.class).onChange(async (value) => {
        currentCSS.class = value;
        await this.plugin.saveSettings();
        this.plugin.addCSSCommand({
          name: currentCSS.name,
          tag: currentCSS.tag,
          class: value,
          style: currentCSS.style,
          contextMenu: currentCSS.contextMenu
        }, cssCounter + 1);
      });
    });
    new import_obsidian.Setting(settingItemContainer).setClass("css-inserter-setting-item-style").addText((text) => {
      return text.setValue(currentCSS.style).onChange(async (value) => {
        currentCSS.style = value;
        await this.plugin.saveSettings();
        this.plugin.addCSSCommand({
          name: currentCSS.name,
          tag: currentCSS.tag,
          class: currentCSS.class,
          style: value,
          contextMenu: currentCSS.contextMenu
        }, cssCounter + 1);
      });
    });
    new import_obsidian.Setting(settingItemContainer).setClass("css-inserter-setting-item-contextMenu").addToggle((toggle) => {
      toggle.setValue(currentCSS.contextMenu).setTooltip((toggle.getValue() ? "Disable" : "Enable") + " in the context menu").onChange(async () => {
        const value = toggle.getValue();
        toggle.setTooltip((value ? "Disable" : "Enable") + " in the context menu");
        currentCSS.contextMenu = value;
        await this.plugin.saveSettings();
      });
    });
    const upDisabled = cssCounter - 1 === 0;
    const upButtonContainer = settingItemContainer.createDiv({ cls: "css-inserter-button-container" });
    if (!upDisabled) {
      const upButton = new import_obsidian.ButtonComponent(upButtonContainer);
      upButton.setIcon("lucide-arrow-up").setClass("css-inserter-delete-css-button").setTooltip("Move up").onClick(() => this.moveCSS("up", cssCounter, css));
    }
    const downDisabled = cssCounter === css.length;
    const downButtonContainer = settingItemContainer.createDiv({ cls: "css-inserter-button-container" });
    if (!downDisabled) {
      const downButton = new import_obsidian.ButtonComponent(downButtonContainer);
      downButton.setIcon("lucide-arrow-down").setClass("css-inserter-delete-css-button").setTooltip("Move down").onClick(() => this.moveCSS("down", cssCounter, css));
    }
    const deleteButtonContainer = settingItemContainer.createDiv({ cls: "css-inserter-button-container" });
    const deleteButton = new import_obsidian.ButtonComponent(deleteButtonContainer);
    deleteButton.setIcon("lucide-trash-2").setClass("css-inserter-delete-css-button").setTooltip("Remove CSS snippet").onClick(async () => {
      this.plugin.settings.css.splice(cssCounter - 1, 1);
      await this.plugin.saveSettings();
      this.display();
    });
    if (!counter)
      setTimeout(() => this.display(), 0);
  }
  async moveCSS(direction, cssCounter, css) {
    this.plugin.settings.css = moveCSS(direction, cssCounter, css);
    await this.plugin.saveSettings();
    this.plugin.settings.css.forEach((css2, index) => {
      this.plugin.addCSSCommand(css2, index + 1);
    });
    this.display();
    function moveCSS(direction2, cssCounter2, css2) {
      const movingCSS = css2.splice(cssCounter2 - 1, 1)[0];
      const newPosition = direction2 === "up" ? cssCounter2 - 2 : cssCounter2;
      const newCSS = [
        ...css2.slice(0, newPosition),
        movingCSS,
        ...css2.slice(newPosition)
      ];
      return newCSS;
    }
  }
  addInstructions(containerEl) {
    const containerInstructions = containerEl.createDiv();
    containerInstructions.addClasses(["container-instructions", "instructions"]);
    const htmlTagList = containerInstructions.createDiv();
    htmlTagList.textContent = "Here is a list of ";
    htmlTagList.createEl("a", { text: "HTML tags", href: "https://www.w3schools.com/tags/default.asp" });
    htmlTagList.appendText(" to use.");
    const styleGuide = containerInstructions.createDiv();
    styleGuide.textContent = "Here is a ";
    styleGuide.createEl("a", { text: "guide", href: "https://www.w3schools.com/html/html_styles.asp" });
    styleGuide.appendText(" on how to format the ");
    styleGuide.createEl("b", { text: "style" });
    styleGuide.appendText(" part of the CSS snippet.");
    styleGuide.createEl("br");
    styleGuide.appendText("Everything within the quotes following ");
    styleGuide.createEl("code", { text: "style=" });
    styleGuide.appendText(" should be entered in the CSS snippet.");
    const commandPalette = containerInstructions.createDiv();
    commandPalette.textContent = "Usage with the ";
    commandPalette.createEl("b", { text: "Command palette" });
    commandPalette.appendText(":");
    const commandPaletteUl = commandPalette.createEl("ul");
    commandPaletteUl.createEl("li", { text: "Select text in the editor" });
    const openCP1 = commandPaletteUl.createEl("li");
    openCP1.textContent = "Open the ";
    openCP1.createEl("b", { text: "Command palette" });
    openCP1.appendText(":");
    const openCPUl1 = commandPaletteUl.createEl("ul");
    const openCPUl1Desktop = openCPUl1.createEl("li");
    openCPUl1Desktop.textContent = "Desktop: ";
    openCPUl1Desktop.createEl("code", { text: "Ctrl" });
    openCPUl1Desktop.appendText(" or ");
    openCPUl1Desktop.createEl("code", { text: "Cmd" });
    openCPUl1Desktop.appendText(" + ");
    openCPUl1Desktop.createEl("code", { text: "P" });
    openCPUl1.createEl("li", { text: "Mobile: Swipe Down" });
    commandPaletteUl.createEl("li", { text: 'Look up the CSS snippet to apply: "CSS Inserter ..."' });
    commandPaletteUl.createEl("li", { text: "Select the CSS snippet: " }).createEl("code", { text: "Enter" });
    const removeSnippet = containerInstructions.createDiv();
    removeSnippet.textContent = "Remove applied CSS snippet:";
    const removeUl = removeSnippet.createEl("ul");
    removeUl.createEl("li", { text: "Select the CSS-ified text in the editor" });
    const openCP2 = removeUl.createEl("li");
    openCP2.textContent = "Open the ";
    openCP2.createEl("b", { text: "Command palette" });
    openCP2.appendText(":");
    const openCPUl2 = removeUl.createEl("ul", { cls: "instructions" });
    const openCPUl2Desktop = openCPUl2.createEl("li");
    openCPUl2Desktop.textContent = "Desktop: ";
    openCPUl2Desktop.createEl("code", { text: "Ctrl" });
    openCPUl2Desktop.appendText(" or ");
    openCPUl2Desktop.createEl("code", { text: "Cmd" });
    openCPUl2Desktop.appendText(" + ");
    openCPUl2Desktop.createEl("code", { text: "P" });
    openCPUl2.createEl("li", { text: "Mobile: Swipe down" });
    removeUl.createEl("li", { text: 'Look up: "CSS Remove"' });
    removeUl.createEl("li", { text: "Select the command: " }).createEl("code", { text: "Enter" });
    const credit = containerInstructions.createDiv();
    credit.textContent = "A fork of ";
    credit.createEl("a", { text: "Style Text", href: "https://github.com/juanjoarranz/style-text-obsidian-plugin" });
    credit.appendText(" created by ");
    credit.createEl("a", { text: "Juanjo Arranz", href: "https://github.com/juanjoarranz" }).createEl("br");
    credit.appendText("Modified by Erika Gozar");
  }
  /* private donate(containerEl: HTMLElement) {
          const donateContainer = containerEl.createEl('div', { cls: 'donate' });
          donateContainer.setCssStyles({ marginTop: '40px' });
  
          let buyMeCoffeeImage = new Image(130);
          buyMeCoffeeImage.src = 'https://cdn.ko-fi.com/cdn/kofi3.png?v=3';
          donateContainer.createEl('a', { href: 'https://ko-fi.com/F1F6H4TAR', text: '' }).appendChild(buyMeCoffeeImage);
  
      } */
};

// main.ts
var CSSInserter = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.CSSInserterInContextMenu = (menu, editor) => {
      const enhancedApp = this.app;
      const settings = this.settings;
      menu.addItem(
        (item) => item.setTitle("Remove CSS").setIcon("lucide-eraser").onClick(() => {
          this.removeCSS(editor);
        })
      );
      function addSnippetItems(menu2) {
        settings.css.forEach((css, index) => {
          if (css.contextMenu) {
            menu2.addItem(
              (item) => item.setTitle(css.name).setIcon("lucide-highlighter").onClick(() => {
                enhancedApp.commands.executeCommandById(`css-inserter:insert-css${index + 1}`);
              })
            );
          }
        });
      }
      const subMenuMobile = new import_obsidian2.Menu();
      if (import_obsidian2.Platform.isMobile)
        addSnippetItems(subMenuMobile);
      menu.addItem((item) => {
        item.setTitle("Insert CSS").setIcon("lucide-highlighter");
        if (import_obsidian2.Platform.isDesktop) {
          const snippetSubMenu = item.setSubmenu();
          addSnippetItems(snippetSubMenu);
        } else {
          item.onClick((ev) => {
            if (ev instanceof MouseEvent)
              subMenuMobile.showAtMouseEvent(ev);
            else
              subMenuMobile.showAtPosition({ x: 20, y: 20 });
          });
        }
      });
    };
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "remove-css",
      name: "Remove CSS",
      icon: "lucide-eraser",
      editorCallback: (editor, view) => {
        this.removeCSS(editor);
      }
    });
    this.settings.css.forEach((css, index) => {
      this.addCSSCommand(css, index + 1);
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", this.CSSInserterInContextMenu)
    );
    this.updateBodyListClass();
    this.addSettingTab(new GeneralSettingsTab(this.app, this));
  }
  async loadSettings() {
    this.settings = { ...DEFAULT_SETTINGS, ...await this.loadData() };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  clearHTMLTags(strToSanitize) {
    return strToSanitize.replace(/(<([^>]+)>)/gi, "");
  }
  betterClearHTMLTags(strToSanitize) {
    let myHTML = new DOMParser().parseFromString(strToSanitize, "text/html");
    return myHTML.body.textContent || "";
  }
  // index: 1-based
  addCSSCommand(css, index) {
    this.addCommand({
      id: `insert-css${index}`,
      name: `${css.name}`,
      icon: "lucide-highlighter",
      editorCallback: (editor, view) => {
        const selection = editor.getSelection();
        let thisClass = "";
        if (`${css.class}` != "") {
          thisClass = ` class="${css.class}"`;
        }
        let thisStyle = "";
        if (`${css.style}` != "") {
          thisStyle = ` style="${css.style}"`;
        }
        editor.replaceSelection(`<${css.tag}${thisClass}${thisStyle}>${selection}</${css.tag}>`);
      }
    });
  }
  removeCSS(editor) {
    const selection = editor.getSelection();
    editor.replaceSelection(this.betterClearHTMLTags(selection));
  }
  updateBodyListClass() {
    document.body.classList.add("css-inserter");
  }
};

/* nosourcemap */